# Arrays & Multi-dimensional arrays

>
> **Terminology**:
>
> *module*: collection of functions \
> *package / library*: collection of modules
>


### Import functions

> **import** *function_name* **as** *synonym*

In [1]:
import numpy as np

### Arrays

In [2]:
# simple array
array_1 = np.array([1, 2, 3, 4, 5])
print(array_1)
type(array_1)

# numpy auto-transforms entries: auto-transformation to string
array_2 = np.array([1, 2, 'three', 4, 5])
print(array_2)

# auto-transform to float
array_3 = np.array([1, 2, 3.0, 4, 5])
print(array_3)

[1 2 3 4 5]
['1' '2' 'three' '4' '5']
[1. 2. 3. 4. 5.]


### Multi-dimensional arrays

In [4]:
# You can create multi-dimensional arrays using NumPy, i.e. lists of lists --> table w columns and rows

array_4 = np.array([[1, 2, 3] , [4, 5, 6]])
print(array_4)
array_4.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [6]:
# Exercise

array_5 = np.array([[1, 2] , [3, 4] , [5, 6]])
print(array_5)
print('---')
print(array_5.shape)

[[1 2]
 [3 4]
 [5 6]]
---
(3, 2)


In [7]:
# .reshape() and .transpose()

print(array_5.reshape(2, 3))
print(array_5.transpose())

[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]
