# Arrays & Multi-dimensional arrays

>
> **Terminology**:
>
> *module*: collection of functions \
> *package / library*: collection of modules
>


### Import functions

> **import** *function_name* **as** *synonym*

In [3]:
import numpy as np

### Arrays

In [2]:
# simple array
array_1 = np.array([1, 2, 3, 4, 5])
print(array_1)
type(array_1)

# numpy auto-transforms entries: auto-transformation to string
array_2 = np.array([1, 2, 'three', 4, 5])
print(array_2)

# auto-transform to float
array_3 = np.array([1, 2, 3.0, 4, 5])
print(array_3)

[1 2 3 4 5]
['1' '2' 'three' '4' '5']
[1. 2. 3. 4. 5.]


### Multi-dimensional arrays

In [4]:
# You can create multi-dimensional arrays using NumPy, i.e. lists of lists --> table w rows and columns

array_4 = np.array([[1, 2, 3] , [4, 5, 6]])
print(array_4)
array_4.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [6]:
# Exercise

array_5 = np.array([[1, 2] , [3, 4] , [5, 6]])
print(array_5)
print('---')
print(array_5.shape)

[[1 2]
 [3 4]
 [5 6]]
---
(3, 2)


In [7]:
# .reshape() and .transpose()

print(array_5.reshape(2, 3))
print(array_5.transpose())

[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


In [4]:
# Exercise

array_a = np.array([
    ['n', 'e', 'w', 'y', '_', 's'],
    ['t', 'o', 'c', 'k', '_', 'r'],
    ['_', '_', '_', 'k', 'e', 'x'],
    ['c', 'h', 'a', 'n', 'g', 'e']
])

1. Create a new array, array_b, by reshaping array_a to 6 rows and 4 colUmns
2. Print array_b
3. Using ranges, print "new york stock exchange" from array_b with a new line for each word you will call the print function four times)

In [5]:
# 1. 

array_b = array_a.reshape(6, 4)

# 2. 

print(array_b)

[['n' 'e' 'w' 'y']
 ['_' 's' 't' 'o']
 ['c' 'k' '_' 'r']
 ['_' '_' '_' 'k']
 ['e' 'x' 'c' 'h']
 ['a' 'n' 'g' 'e']]


In [31]:
# 3. 

print(array_b[0, :3])
print(array_b[:4, 3])
print(array_b[1, 1:], array_b[2, :2])
print(array_b[4, :], array_b[5, :])

['n' 'e' 'w']
['y' 'o' 'r' 'k']
['s' 't' 'o'] ['c' 'k']
['e' 'x' 'c' 'h'] ['a' 'n' 'g' 'e']


In [32]:
# calculating with arrays

array_x = np.array([
    [1, 2],
    [3, 4]
])

array_y = np.array([
    [5, 6],
    [7, 8]
])

In [38]:
# sum

array_z = array_x + array_y
print(array_z)
print('---')
print(array_z + 10)

[[ 6  8]
 [10 12]]
---
[[16 18]
 [20 22]]


# NumPy Aggregation functions

`np.sum()` \
`np.min()` \
`np.max()` \
`np.median()` \
`np.mean()` \
`np.std()` 

In [42]:
print(array_z)
print('---')
print('Sum of all objects = {}'.format(np.sum(array_z)))
print('Min value = {}'.format(np.min(array_z)))
print('Max value = {}'.format(np.max(array_z)))

[[ 6  8]
 [10 12]]
---
Sum of all objects = 36
Min value = 6
Max value = 12


Aggregation functions are designed to accept `axis=n` arguement!

In [44]:
print('Min value by row = {}'.format(np.min(array_z, axis=0)))
print('Max value by row = {}'.format(np.max(array_z, axis=0)))

Min value by row = [6 8]
Max value by row = [10 12]


In [45]:
print('Min value by columns = {}'.format(np.min(array_z, axis=1)))
print('Max value by columns = {}'.format(np.max(array_z, axis=1)))

Min value by columns = [ 6 10]
Max value by columns = [ 8 12]


In [46]:
# Exercise

current_prices = np.array([
    [223.84, 113.5, 139.49],
    [113.37, 30.37, 265.31],
    [1177.98, 54.73, 42.96],
])

target_prices = np.array([
    [232.27, 112.15, 144.2],
    [122.3, 34.33, 284.14],
    [1384.89, 62.12, 43.06],
])

1. Create a new array called price_increases by subtracting current_prices from target_prices
2. Print price_increases
3. Create a new array called returns by dividing price_increases by current_prices and rounding the result to
3 decimal places
4. Print returns
5. Print the maximum value in returns
6. Print the mean returns for each industry column rounded to 3 decimal places

In [47]:
# 1.

price_increases = target_prices - current_prices

# 2.

print(price_increases)

[[ 8.4300e+00 -1.3500e+00  4.7100e+00]
 [ 8.9300e+00  3.9600e+00  1.8830e+01]
 [ 2.0691e+02  7.3900e+00  1.0000e-01]]


In [51]:
# 3. 

returns = np.round((price_increases / current_prices), 3)

# 4.

print(returns)

[[ 0.038 -0.012  0.034]
 [ 0.079  0.13   0.071]
 [ 0.176  0.135  0.002]]


In [52]:
# 5. 

print('Max value in returns: {}'.format(np.max(returns)))

Max value in returns: 0.176


In [59]:
# 6. 

print('Mean return per industry: {}'.format(np.round(np.mean(returns, axis=0),3)))
print('Mean return in TECH: {}'.format(np.round(np.mean(returns[:,0]),3)))
print('Mean return in FINANCIALS: {}'.format(np.round(np.mean(returns[:,1]),3)))
print('Mean return in HEALTHCARE: {}'.format(np.round(np.mean(returns[:,2]),3)))

Mean return per industry: [0.098 0.084 0.036]
Mean return in TECH: 0.098
Mean return in FINANCIALS: 0.084
Mean return in HEALTHCARE: 0.036
