# Random & Sequences

In [2]:
import numpy as np

In [15]:
# low = first to INCLUDE
# high = first to EXCLUDE
# size = how MANY numbers --can pass shape of array, e.g (5, 2)

print ( np.random.randint(low=1, high=11, size=1) )

[1]


In [16]:
rand_array = np.random.randint(low=1, high=11, size=10)
print(rand_array)
print(rand_array.shape)

[ 1 10  4  5  1  1  5  2  8  4]
(10,)


In [6]:
rand_array = rand_array.reshape(5, 2)
print(rand_array)

[[10  9]
 [10  5]
 [ 4  7]
 [ 4  5]
 [ 4 10]]


> `.seed()` = output still random, but will show same random output when cell run again

In [ ]:
np.random.seed(123)

rand_array = np.random.randint(low=1, high=11, size=(5, 2))

print(rand_array)

[[ 3  3]
 [ 7  2]
 [ 4 10]
 [ 7  2]
 [ 1  2]]


> `.random.choice()`

In [22]:
ordered_array = np.array(range(1, 11))
print(ordered_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [24]:
np.random.seed(10)

# randomly picks from list 10 times
print(np.random.choice(ordered_array, 5))

# randomly picks 10 without 'putting back', e.g. lottery numbers
print(np.random.choice(ordered_array, 5, replace=False))

[10  5  1  2 10]
[6 4 5 8 7]


In [ ]:
# Exercise

1. Set the random seed to 99
2. Generate an array of random integers between 1 and
25 named rand _array with 5 rows and 5 columns
3. Print rand_array
4. Choose and print a random sample of 5 numbers from the second row of rand_array with replacement
5. Generate an array of ordered integers from 1 to 25 named ordered_array and reshape to 5 rows and 5
colUmns
6. Print ordered_array
7. Choose and print a random sample of 5 numbers from the third column of ordered _array without replacement

In [25]:
# 1. 

np.random.seed(99)

In [26]:
# 2. 

rand_array = np.random.randint(low=1, high=26, size=(5,5))

# 3.
print(rand_array)

[[ 2  4  9 10  9]
 [19  5  6 21  2]
 [24  4 24 18  2]
 [17  7 12 21 24]
 [ 3  1 13  9  9]]


In [28]:
# 4. 

print(
    np.random.choice(rand_array[1,:], 5)
)

[ 2  5 21  6 21]


In [30]:
# 5. 

ordered_array = np.array(range(1,26))
ordered_array = ordered_array.reshape(5, 5)

# 6.

print(ordered_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [33]:
# 7.

print(
    np.random.choice(ordered_array[:,2], 5, replace=False)
)

[23  3 13 18  8]
